// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CardGameApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220921125236_initialUpdate")]
    partial class initialUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entites.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Suit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "/images/hearts/ace.png",
                            IsActive = true,
                            Number = 14,
                            Suit = 0
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "/images/hearts/2.png",
                            IsActive = true,
                            Number = 2,
                            Suit = 0
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "/images/hearts/3.png",
                            IsActive = true,
                            Number = 3,
                            Suit = 0
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "/images/hearts/4.png",
                            IsActive = true,
                            Number = 4,
                            Suit = 0
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "/images/hearts/5.png",
                            IsActive = true,
                            Number = 5,
                            Suit = 0
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "/images/hearts/6.png",
                            IsActive = true,
                            Number = 6,
                            Suit = 0
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "/images/hearts/7.png",
                            IsActive = true,
                            Number = 7,
                            Suit = 0
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "/images/hearts/8.png",
                            IsActive = true,
                            Number = 8,
                            Suit = 0
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "/images/hearts/9.png",
                            IsActive = true,
                            Number = 9,
                            Suit = 0
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "/images/hearts/10.png",
                            IsActive = true,
                            Number = 10,
                            Suit = 0
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "/images/hearts/jack.png",
                            IsActive = true,
                            Number = 11,
                            Suit = 0
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "/images/hearts/queen.png",
                            IsActive = true,
                            Number = 12,
                            Suit = 0
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "/images/hearts/king.png",
                            IsActive = true,
                            Number = 13,
                            Suit = 0
                        });
                });

            modelBuilder.Entity("Entites.Models.HandHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardIdFive")
                        .HasColumnType("int");

                    b.Property<int>("CardIdFour")
                        .HasColumnType("int");

                    b.Property<int>("CardIdOne")
                        .HasColumnType("int");

                    b.Property<int>("CardIdThree")
                        .HasColumnType("int");

                    b.Property<int>("CardIdTwo")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HandHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
