// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CardGameApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entites.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Suit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "/images/hearts/ace.png",
                            IsActive = true,
                            Number = 14,
                            Suit = 0
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "/images/hearts/2.png",
                            IsActive = true,
                            Number = 2,
                            Suit = 0
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "/images/hearts/3.png",
                            IsActive = true,
                            Number = 3,
                            Suit = 0
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "/images/hearts/4.png",
                            IsActive = true,
                            Number = 4,
                            Suit = 0
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "/images/hearts/5.png",
                            IsActive = true,
                            Number = 5,
                            Suit = 0
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "/images/hearts/6.png",
                            IsActive = true,
                            Number = 6,
                            Suit = 0
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "/images/hearts/7.png",
                            IsActive = true,
                            Number = 7,
                            Suit = 0
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "/images/hearts/8.png",
                            IsActive = true,
                            Number = 8,
                            Suit = 0
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "/images/hearts/9.png",
                            IsActive = true,
                            Number = 9,
                            Suit = 0
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "/images/hearts/10.png",
                            IsActive = true,
                            Number = 10,
                            Suit = 0
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "/images/hearts/jack.png",
                            IsActive = true,
                            Number = 11,
                            Suit = 0
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "/images/hearts/queen.png",
                            IsActive = true,
                            Number = 12,
                            Suit = 0
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "/images/hearts/king.png",
                            IsActive = true,
                            Number = 13,
                            Suit = 0
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "/images/diamonds/ace.png",
                            IsActive = true,
                            Number = 14,
                            Suit = 2
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "/images/diamonds/2.png",
                            IsActive = true,
                            Number = 2,
                            Suit = 2
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "/images/diamonds/3.png",
                            IsActive = true,
                            Number = 3,
                            Suit = 2
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "/images/diamonds/4.png",
                            IsActive = true,
                            Number = 4,
                            Suit = 2
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "/images/diamonds/5.png",
                            IsActive = true,
                            Number = 5,
                            Suit = 2
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "/images/diamonds/6.png",
                            IsActive = true,
                            Number = 6,
                            Suit = 2
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "/images/diamonds/7.png",
                            IsActive = true,
                            Number = 7,
                            Suit = 2
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "/images/diamonds/8.png",
                            IsActive = true,
                            Number = 8,
                            Suit = 2
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "/images/diamonds/9.png",
                            IsActive = true,
                            Number = 9,
                            Suit = 2
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "/images/diamonds/10.png",
                            IsActive = true,
                            Number = 10,
                            Suit = 2
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "/images/diamonds/jack.png",
                            IsActive = true,
                            Number = 11,
                            Suit = 2
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "/images/diamonds/queen.png",
                            IsActive = true,
                            Number = 12,
                            Suit = 2
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "/images/diamonds/king.png",
                            IsActive = true,
                            Number = 13,
                            Suit = 2
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "/images/spades/ace.png",
                            IsActive = true,
                            Number = 14,
                            Suit = 3
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "/images/spades/2.png",
                            IsActive = true,
                            Number = 2,
                            Suit = 3
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "/images/spades/3.png",
                            IsActive = true,
                            Number = 3,
                            Suit = 3
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "/images/spades/4.png",
                            IsActive = true,
                            Number = 4,
                            Suit = 3
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "/images/spades/5.png",
                            IsActive = true,
                            Number = 5,
                            Suit = 3
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "/images/spades/6.png",
                            IsActive = true,
                            Number = 6,
                            Suit = 3
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "/images/spades/7.png",
                            IsActive = true,
                            Number = 7,
                            Suit = 3
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "/images/spades/8.png",
                            IsActive = true,
                            Number = 8,
                            Suit = 3
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "/images/spades/9.png",
                            IsActive = true,
                            Number = 9,
                            Suit = 3
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "/images/spades/10.png",
                            IsActive = true,
                            Number = 10,
                            Suit = 3
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "/images/spades/jack.png",
                            IsActive = true,
                            Number = 11,
                            Suit = 3
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "/images/spades/queen.png",
                            IsActive = true,
                            Number = 12,
                            Suit = 3
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "/images/spades/king.png",
                            IsActive = true,
                            Number = 13,
                            Suit = 3
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "/images/clubs/ace.png",
                            IsActive = true,
                            Number = 14,
                            Suit = 1
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "/images/clubs/2.png",
                            IsActive = true,
                            Number = 2,
                            Suit = 1
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "/images/clubs/3.png",
                            IsActive = true,
                            Number = 3,
                            Suit = 1
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "/images/clubs/4.png",
                            IsActive = true,
                            Number = 4,
                            Suit = 1
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "/images/clubs/5.png",
                            IsActive = true,
                            Number = 5,
                            Suit = 1
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "/images/clubs/6.png",
                            IsActive = true,
                            Number = 6,
                            Suit = 1
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "/images/clubs/7.png",
                            IsActive = true,
                            Number = 7,
                            Suit = 1
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "/images/clubs/8.png",
                            IsActive = true,
                            Number = 8,
                            Suit = 1
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "/images/clubs/9.png",
                            IsActive = true,
                            Number = 9,
                            Suit = 1
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "/images/clubs/10.png",
                            IsActive = true,
                            Number = 10,
                            Suit = 1
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "/images/clubs/jack.png",
                            IsActive = true,
                            Number = 11,
                            Suit = 1
                        },
                        new
                        {
                            Id = 51,
                            ImgUrl = "/images/clubs/queen.png",
                            IsActive = true,
                            Number = 12,
                            Suit = 1
                        },
                        new
                        {
                            Id = 52,
                            ImgUrl = "/images/clubs/king.png",
                            IsActive = true,
                            Number = 13,
                            Suit = 1
                        });
                });

            modelBuilder.Entity("Entites.Models.HandHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardIdFive")
                        .HasColumnType("int");

                    b.Property<int>("CardIdFour")
                        .HasColumnType("int");

                    b.Property<int>("CardIdOne")
                        .HasColumnType("int");

                    b.Property<int>("CardIdThree")
                        .HasColumnType("int");

                    b.Property<int>("CardIdTwo")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HandHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
